apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  ttlSecondsAfterEmpty: 30  
  requirements:
    - key: "karpenter.k8s.aws/instance-category"
      operator: In
      values: ["t","m","c"]
    - key: "karpenter.k8s.aws/instance-cpu"
      operator: In
      values: ["2","4", "8"]
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["spot"]
  limits:
    resources:
      cpu: 1000
  providerRef:
    name: karp-spot-provider
---
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: karp-spot-provider
spec:
  subnetSelector:
    karpenter.sh/discovery: "eks-op-mumbai-d01" # replace with your cluster name
  securityGroupSelector:
    karpenter.sh/discovery: "eks-op-mumbai-d01" # replace with your cluster name
