apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
  name: elasticsearch-pvc
  namespace: es-logging
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: gp2
  volumeMode: Filesystem
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
