# fluent-bit-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: kube-system
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush        5
        Log_Level    info
        Parsers_File parsers.conf
        HTTP_Server  On
        HTTP_Listen  0.0.0.0
        HTTP_Port    2020

    @INCLUDE input-containerd.conf
    @INCLUDE filter-kubernetes.conf
    @INCLUDE output-elasticsearch.conf

  input-containerd.conf: |
    [INPUT]
        Name                tail
        Tag                 containerd.*
        Path                /var/log/containers/*.log
        Parser              containerd
        DB                  /var/log/flb_containerd.db
        Mem_Buf_Limit       100MB
        Skip_Long_Lines     On
        Refresh_Interval    10

  parsers.conf: |
    [PARSER]
        Name        containerd
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L%z
        # Define the regular expression to extract the container id.
        # Example: /var/lib/docker/containers/67a1830e0cf891b6e16b3ec247b33fbac7b1e826d70aa1a25a689fb719cfafff/67a1830e0cf891b6e16b3ec247b33fbac7b1e826d70aa1a25a689fb719cfafff-json.log
        #   container_id = 67a1830e0cf891b6e16b3ec247b33fbac7b1e826d70aa1a25a689fb719cfafff
        REGEX ^/var/log/containers/(?<container_id>[^_]+)_(?<source_name>[^_]+)_(?<namespace>[^_]+)-(?<pod_name>[^_]+)_(?<container_name>.+)-(?<container_id_with_extra_info>[[:alnum:]]{64})\.log$

