apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: es-logging
spec:
  selector:
    matchLabels:
      app: kibana
  replicas: 1
  template:
    metadata:
      labels:
        app: kibana
    spec:
      tolerations:
        - effect: NoSchedule
          key: logging
          operator: Equal
          value: "true"
        - effect: NoSchedule
          key: spot
          operator: Equal
          value: "true"
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: eks.amazonaws.com/capacityType
                operator: In
                values:
                - SPOT
            weight: 1
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:7.11.2
        ports:
        - containerPort: 5601
          name: http
          protocol: TCP
        env:
        - name: ELASTICSEARCH_URL
          value: "http://elasticsearch:9200"

