--- 
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: eks-op-mumbai-d01
  region: ap-south-1
  version: "1.24"
vpc:
  id: vpc-0de5e83570239a534
  subnets:
    private:
      ap-south-1a:
        id: subnet-0f91f6f7645c60d33
      ap-south-1b:
        id: subnet-001fc09130a60060b
    public:
      ap-south-1a:
        id: subnet-0949985b93e11b0e5
      ap-south-1b:
        id: subnet-09889ef804031915e
iam:
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: cluster-autoscaler
      namespace: kube-system
    wellKnownPolicies:
      autoScaler: true
    roleName: eksctl-cluster-autoscaler
    roleOnly: true
managedNodeGroups:
- name: gpnodepool
  tags:
    # EC2 tags required for cluster-autoscaler auto-discovery
    k8s.io/cluster-autoscaler/enabled: "true"
    k8s.io/cluster-autoscaler/eks-op-mumbai-d01: "owned"
  privateNetworking: true
  instanceType: t3a.large  
  desiredCapacity: 1
  minSize: 1
  maxSize: 2
- name: spotpool
  tags:
    # EC2 tags required for cluster-autoscaler auto-discovery
    k8s.io/cluster-autoscaler/enabled: "true"
    k8s.io/cluster-autoscaler/eks-op-mumbai-d01: "owned"
  privateNetworking: true
  instanceType: t3a.medium
  spot: true
  desiredCapacity: 1
  minSize: 1
  maxSize: 3
  labels:
    role: spot
  taints:
  - key: spot
    value: "true"
    effect: NoSchedule