apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
  name: maven-cache
  namespace: jenkins
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: gp2
  volumeMode: Filesystem
