apiVersion: apps/v1
kind: Deployment
metadata:
  name: alert-engine 
  labels:
    app: alert-engine
spec:
  selector:
    matchLabels:
      app: alert-engine
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: alert-engine
    spec:
      containers:
      - name: alert-engine
        image: 476843538485.dkr.ecr.ap-south-1.amazonaws.com/alert-engine:5
        imagePullPolicy: Always
        ports:
        - containerPort: 9055
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "500Mi"
            cpu: "500m"


---

apiVersion: v1
kind: Service
metadata:
  name: alert-engine
spec:
  selector:
    app: alert-engine
  ports:
  - name: http
    port: 9055
    protocol: TCP
    targetPort: 9055 

---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  labels:
    name: alert-engine
  name: alert-engine
spec:
  gateways:
  - outpath-com
  hosts:
  - alert-engine-develop.outpathstg.com
  - alert-engine-develop
  http:
  - route:
    - destination:
        host: alert-engine
        port:
          number: 9055