apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: awssm-external-secret
spec:
  secretStoreRef:
    name: awssm-secretstore
    kind: SecretStore  # or ClusterSecretStore
  refreshInterval: "1h"
  target:
    name: alert-engine-develop
    creationPolicy: 'Owner'
  data:
    - secretKey: username
      remoteRef:
        key: alert-engine-develop
        property: username
    - secretKey: password
      remoteRef:
        key: alert-engine-develop
        property: password
  