apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: awssm-secretstore
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-south-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: awssm-secret
            key: accessKeyID
          secretAccessKeySecretRef:
            name: awssm-secret
            key: secretAccessKey
