apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sample-secret
  namespace: default
spec:
  encryptedData:
    password: AgBYcHxFX3c8LkcJet3w1nYk59+PYj0HblVrS8P58oxf5QM5nNdUmcvv+rM/t5y1Bot7B7jzt4ImbCfWeWQ3CClTV4AMSd+x7T0oBXWDLxmrUb+0l3IOk88DU6dGbicA89JHdhAiTIGPuF8crncv31Z0l6xIPs/dlW2x7JQs1PZUUw1duhxOWGNx1mF152oJL4wFV20afKvzc5iBjGGiK6dHwAWQIwfzHBcv78ifIqgBVruYb18BMCFc+N1LsI0O6iClonlWGLOGxn3M1x4k2fmndy9BLujTQW0cRdsFJmNOX/AL5QQnrzFsXh8nakclv3igNeLOGxZUkh4n3S67HzDKbccX9qfEtiO6UuPpg7ZBQuF/OeRjtKFXLgQeXdwhUzJywJjJe8v/htl09zCF+nlP1wQwerYq2nz2Ff7Dp0hYhBJd6DGUO5d1Vw09EyBOp5yuFYQ36CtG+DzUzg2QOKcuUfY1YGrRRV51h+HuAtCZEUFf3CCIXhiDC4nEbysiJrN7xtHnD+yDLz5stUMbTkhth72Qj7RA4fV0adGucqrZyK9ipAPW0snhfnPtTOD2Geqb/u1hQaYMD6LpQhb6SlmnbT7rt3nfJyUfevLkdFeVLudoPh/i6R3msCNtOIK/p9PZLLBXicIWRpWiflqKdxc82TYHK/BQD6w+6jEhj1ViK16pLLq5jMuTnNUFRvFAIP3wPLk9Bg==
    username: AgBMdCZwLmI6y39/vhNuX47Ols5R5bQOpI2VbRClQzdG0dzh6ofA4SIQyYQPqBm7v4I1h3eAbT7aBjt4GQ2O2fp8jdFLuCJ1XgNKhxuTA/lRVllYBc9bJBtP+BdWrogcKqdKWyisyHS3njacK1TE67q+lhrsv/apTm6oU5oGJE4QFFOcW76w3HSGnqN0GPPh1Gy4ylUX5kNMhs3P5FsS9UrahpQOw/TLSopk28lH1djZyKdu6AKc+txa3qdB1Si2CJwO/bRtlHGtqPm8vAP8BG0gEbmbDOxmblu9eHhp2X6PPgRNQztjBXIM/22wJ9emcDqOLFos2UEDF6LIoVA3BMdEr3Jt4WqaD9mpDf8UAQ9yy2wwQodz4+Rv77DRdOoDGszC35YlMGamLwSeoRDdOQW4ba93geyA1VBxwDGQk0/sfgT5K9ykQ1NqMnvOfhKIjSMzB4Z3mF3Dqbq2XsQSOkwbV5NRZdRN33tcOiMb3c9YmkGHR2u/piAW/zTWpf3RblXsqQogdQ34oHJXrGcr0YPr2ZJ0Ta+ueH3L5+k8Yq6wicfgNCG9zTmdkQzRAyyEaYN/kNTxuffCSGGygfiNdvHa0wkkjh0W+0aC8y3+6NGPB7cEmlOxLbQE728ByhHkzyqZZzWb0bdkVVYy1Btw7dAoRDcZUoG89hwjwYw/jD3+e62bPRz/G1utQuhE+V9VARIq+zB5qTEVdOo=
  template:
    metadata:
      creationTimestamp: null
      name: sample-secret
      namespace: default

